// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: broker.proto

package broker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domname string `protobuf:"bytes,1,opt,name=domname,proto3" json:"domname,omitempty"`
}

func (x *Dom) Reset() {
	*x = Dom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dom) ProtoMessage() {}

func (x *Dom) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dom.ProtoReflect.Descriptor instead.
func (*Dom) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{0}
}

func (x *Dom) GetDomname() string {
	if x != nil {
		return x.Domname
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

var File_broker_proto protoreflect.FileDescriptor

var file_broker_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x22, 0x1f, 0x0a, 0x03, 0x64, 0x6f, 0x6d, 0x12, 0x18, 0x0a,
	0x07, 0x64, 0x6f, 0x6d, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x64, 0x6f, 0x6d, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x70, 0x32, 0x45, 0x0a, 0x0d, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x44,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x0b, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x64,
	0x6f, 0x6d, 0x1a, 0x10, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x42, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_broker_proto_rawDescOnce sync.Once
	file_broker_proto_rawDescData = file_broker_proto_rawDesc
)

func file_broker_proto_rawDescGZIP() []byte {
	file_broker_proto_rawDescOnce.Do(func() {
		file_broker_proto_rawDescData = protoimpl.X.CompressGZIP(file_broker_proto_rawDescData)
	})
	return file_broker_proto_rawDescData
}

var file_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_broker_proto_goTypes = []interface{}{
	(*Dom)(nil),      // 0: broker.dom
	(*Response)(nil), // 1: broker.response
}
var file_broker_proto_depIdxs = []int32{
	0, // 0: broker.BrokerHandler.ConnectDomain:input_type -> broker.dom
	1, // 1: broker.BrokerHandler.ConnectDomain:output_type -> broker.response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_broker_proto_init() }
func file_broker_proto_init() {
	if File_broker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_broker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_broker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_broker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_broker_proto_goTypes,
		DependencyIndexes: file_broker_proto_depIdxs,
		MessageInfos:      file_broker_proto_msgTypes,
	}.Build()
	File_broker_proto = out.File
	file_broker_proto_rawDesc = nil
	file_broker_proto_goTypes = nil
	file_broker_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BrokerHandlerClient is the client API for BrokerHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BrokerHandlerClient interface {
	ConnectDomain(ctx context.Context, opts ...grpc.CallOption) (BrokerHandler_ConnectDomainClient, error)
}

type brokerHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerHandlerClient(cc grpc.ClientConnInterface) BrokerHandlerClient {
	return &brokerHandlerClient{cc}
}

func (c *brokerHandlerClient) ConnectDomain(ctx context.Context, opts ...grpc.CallOption) (BrokerHandler_ConnectDomainClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BrokerHandler_serviceDesc.Streams[0], "/broker.BrokerHandler/ConnectDomain", opts...)
	if err != nil {
		return nil, err
	}
	x := &brokerHandlerConnectDomainClient{stream}
	return x, nil
}

type BrokerHandler_ConnectDomainClient interface {
	Send(*Dom) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type brokerHandlerConnectDomainClient struct {
	grpc.ClientStream
}

func (x *brokerHandlerConnectDomainClient) Send(m *Dom) error {
	return x.ClientStream.SendMsg(m)
}

func (x *brokerHandlerConnectDomainClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BrokerHandlerServer is the server API for BrokerHandler service.
type BrokerHandlerServer interface {
	ConnectDomain(BrokerHandler_ConnectDomainServer) error
}

// UnimplementedBrokerHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedBrokerHandlerServer struct {
}

func (*UnimplementedBrokerHandlerServer) ConnectDomain(BrokerHandler_ConnectDomainServer) error {
	return status.Errorf(codes.Unimplemented, "method ConnectDomain not implemented")
}

func RegisterBrokerHandlerServer(s *grpc.Server, srv BrokerHandlerServer) {
	s.RegisterService(&_BrokerHandler_serviceDesc, srv)
}

func _BrokerHandler_ConnectDomain_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrokerHandlerServer).ConnectDomain(&brokerHandlerConnectDomainServer{stream})
}

type BrokerHandler_ConnectDomainServer interface {
	Send(*Response) error
	Recv() (*Dom, error)
	grpc.ServerStream
}

type brokerHandlerConnectDomainServer struct {
	grpc.ServerStream
}

func (x *brokerHandlerConnectDomainServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *brokerHandlerConnectDomainServer) Recv() (*Dom, error) {
	m := new(Dom)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _BrokerHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "broker.BrokerHandler",
	HandlerType: (*BrokerHandlerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectDomain",
			Handler:       _BrokerHandler_ConnectDomain_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "broker.proto",
}
